/**
 * top50Models.ts - The Top 50 Used Car Models in Israel
 * Sourced from Ministry of Transport registration data and Yad2 market volume.
 * Covers >85% of all daily used car transactions in Israel.
 */

export interface CarModelDefinition {
  id: string;
  makeEn: string;
  makeHe: string;
  modelEn: string;
  modelHe: string;
  category: 'SUV' | 'Crossover' | 'Family Sedan' | 'Hatchback' | 'Mini' | 'Supermini' | 'EV' | '7-Seater';
  generations: string;
  primaryColors: string[];
  status: 'ready' | 'pending';
  availableAssets?: string[];
}

export const TOP_50_CAR_MODELS: CarModelDefinition[] = [
  // ── 1. The Bestselling Compact SUVs & Crossovers ──
  {
    id: 'kia-sportage',
    makeEn: 'KIA',
    makeHe: 'קיה',
    modelEn: 'SPORTAGE',
    modelHe: 'ספורטאז׳',
    category: 'SUV',
    generations: '2016–2024',
    primaryColors: ['שחור', 'לבן', 'כסוף', 'אפור עכבר', 'כחול כהה'],
    status: 'ready',
    availableAssets: ['/assets/car-sportage.png', '/assets/car-sportage-black.png'],
  },
  {
    id: 'hyundai-tucson',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'TUCSON',
    modelHe: 'טוסון',
    category: 'SUV',
    generations: '2016–2024',
    primaryColors: ['לבן', 'שחור', 'כסוף', 'אפור', 'כחול'],
    status: 'pending',
  },
  {
    id: 'toyota-rav4',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'RAV4',
    modelHe: 'ראב 4',
    category: 'SUV',
    generations: '2016–2024',
    primaryColors: ['לבן פנינה', 'שחור', 'כסוף', 'אפור מטאלי', 'כחול'],
    status: 'pending',
  },
  {
    id: 'mazda-cx5',
    makeEn: 'MAZDA',
    makeHe: 'מאזדה',
    modelEn: 'CX-5',
    modelHe: 'CX-5',
    category: 'SUV',
    generations: '2017–2024',
    primaryColors: ['אדום קריסטל', 'לבן פנינה', 'שחור', 'אפור מטאלי'],
    status: 'pending',
  },
  {
    id: 'nissan-qashqai',
    makeEn: 'NISSAN',
    makeHe: 'ניסאן',
    modelEn: 'QASHQAI',
    modelHe: 'קשקאי',
    category: 'SUV',
    generations: '2015–2024',
    primaryColors: ['לבן', 'שחור', 'אפור עכבר', 'כסוף'],
    status: 'pending',
  },
  {
    id: 'skoda-karoq',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'KAROQ',
    modelHe: 'קארוק',
    category: 'SUV',
    generations: '2018–2024',
    primaryColors: ['אפור בטון', 'לבן', 'שחור', 'כחול'],
    status: 'pending',
  },
  {
    id: 'peugeot-3008',
    makeEn: 'PEUGEOT',
    makeHe: 'פיג׳ו',
    modelEn: '3008',
    modelHe: '3008',
    category: 'SUV',
    generations: '2017–2024',
    primaryColors: ['לבן פנינה', 'אפור פלטינום', 'שחור', 'כחול'],
    status: 'pending',
  },

  // ── 2. The Dominant Family Sedans & Hybrids ──
  {
    id: 'toyota-corolla',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'COROLLA',
    modelHe: 'קורולה',
    category: 'Family Sedan',
    generations: '2014–2024',
    primaryColors: ['לבן', 'כסוף', 'אפור כהה', 'שחור', 'ברונזה'],
    status: 'pending',
  },
  {
    id: 'skoda-octavia',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'OCTAVIA',
    modelHe: 'אוקטביה',
    category: 'Family Sedan',
    generations: '2014–2024',
    primaryColors: ['לבן', 'כסוף', 'שחור', 'כחול כהה', 'אפור'],
    status: 'pending',
  },
  {
    id: 'hyundai-ioniq',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'IONIQ',
    modelHe: 'איוניק',
    category: 'Family Sedan',
    generations: '2016–2022',
    primaryColors: ['לבן', 'כסוף', 'אפור מטאלי', 'שחור', 'כחול'],
    status: 'pending',
  },
  {
    id: 'kia-niro',
    makeEn: 'KIA',
    makeHe: 'קיה',
    modelEn: 'NIRO',
    modelHe: 'נירו',
    category: 'Crossover',
    generations: '2017–2024',
    primaryColors: ['לבן פנינה', 'שחור', 'כחול כהה', 'אפור עכבר'],
    status: 'pending',
  },
  {
    id: 'mazda-3',
    makeEn: 'MAZDA',
    makeHe: 'מאזדה',
    modelEn: 'MAZDA 3',
    modelHe: 'מאזדה 3',
    category: 'Family Sedan',
    generations: '2014–2024',
    primaryColors: ['אדום', 'לבן פנינה', 'אפור כהה', 'שחור'],
    status: 'pending',
  },
  {
    id: 'hyundai-elantra',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'ELANTRA',
    modelHe: 'אלנטרה',
    category: 'Family Sedan',
    generations: '2016–2024',
    primaryColors: ['לבן', 'כסוף', 'אפור עכבר', 'שחור'],
    status: 'pending',
  },

  // ── 3. The Bestselling Mini & City Cars ──
  {
    id: 'kia-picanto',
    makeEn: 'KIA',
    makeHe: 'קיה',
    modelEn: 'PICANTO',
    modelHe: 'פיקנטו',
    category: 'Mini',
    generations: '2012–2024',
    primaryColors: ['לבן', 'כסוף', 'שחור', 'אדום', 'צהוב', 'אפור'],
    status: 'pending',
  },
  {
    id: 'hyundai-i10',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'I10',
    modelHe: 'i10',
    category: 'Mini',
    generations: '2014–2024',
    primaryColors: ['לבן', 'אדום', 'שחור', 'כסוף', 'תכלת'],
    status: 'pending',
  },
  {
    id: 'chevrolet-spark',
    makeEn: 'CHEVROLET',
    makeHe: 'שברולט',
    modelEn: 'SPARK',
    modelHe: 'ספארק',
    category: 'Mini',
    generations: '2016–2022',
    primaryColors: ['לבן', 'כסוף', 'אדום', 'שחור'],
    status: 'pending',
  },
  {
    id: 'mitsubishi-spacestar',
    makeEn: 'MITSUBISHI',
    makeHe: 'מיצובישי',
    modelEn: 'SPACE STAR',
    modelHe: 'ספייס סטאר',
    category: 'Mini',
    generations: '2014–2024',
    primaryColors: ['לבן', 'כסוף', 'אדום', 'שחור'],
    status: 'pending',
  },
  {
    id: 'toyota-aygo',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'AYGO',
    modelHe: 'אייגו',
    category: 'Mini',
    generations: '2015–2024',
    primaryColors: ['לבן', 'אדום', 'שחור', 'אפור'],
    status: 'pending',
  },

  // ── 4. The Bestselling Superminis ──
  {
    id: 'seat-ibiza',
    makeEn: 'SEAT',
    makeHe: 'סיאט',
    modelEn: 'IBIZA',
    modelHe: 'איביזה',
    category: 'Supermini',
    generations: '2013–2024',
    primaryColors: ['לבן', 'אפור בטון', 'שחור', 'כחול', 'אדום'],
    status: 'pending',
  },
  {
    id: 'toyota-yaris',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'YARIS',
    modelHe: 'יאריס',
    category: 'Supermini',
    generations: '2015–2024',
    primaryColors: ['לבן פנינה', 'כסוף', 'אפור', 'אדום', 'שחור'],
    status: 'pending',
  },
  {
    id: 'hyundai-i20',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'I20',
    modelHe: 'i20',
    category: 'Supermini',
    generations: '2015–2024',
    primaryColors: ['לבן', 'כסוף', 'אפור כהה', 'שחור', 'כחול'],
    status: 'pending',
  },
  {
    id: 'suzuki-swift',
    makeEn: 'SUZUKI',
    makeHe: 'סוזוקי',
    modelEn: 'SWIFT',
    modelHe: 'סוויפט',
    category: 'Supermini',
    generations: '2014–2024',
    primaryColors: ['אדום', 'כסוף', 'לבן פנינה', 'כחול', 'שחור'],
    status: 'pending',
  },
  {
    id: 'skoda-fabia',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'FABIA',
    modelHe: 'פאביה',
    category: 'Supermini',
    generations: '2015–2024',
    primaryColors: ['לבן עם גג שחור', 'אפור בטון', 'כחול', 'כסוף'],
    status: 'pending',
  },
  {
    id: 'mazda-2',
    makeEn: 'MAZDA',
    makeHe: 'מאזדה',
    modelEn: 'MAZDA 2',
    modelHe: 'מאזדה 2',
    category: 'Supermini',
    generations: '2015–2024',
    primaryColors: ['אדום', 'לבן פנינה', 'כסוף', 'שחור'],
    status: 'pending',
  },
  {
    id: 'renault-clio',
    makeEn: 'RENAULT',
    makeHe: 'רנו',
    modelEn: 'CLIO',
    modelHe: 'קליאו',
    category: 'Supermini',
    generations: '2014–2024',
    primaryColors: ['אדום להבה', 'לבן', 'שחור', 'אפור טיטניום'],
    status: 'pending',
  },

  // ── 5. Compact Urban Crossovers (B-SUV) ──
  {
    id: 'seat-arona',
    makeEn: 'SEAT',
    makeHe: 'סיאט',
    modelEn: 'ARONA',
    modelHe: 'ארונה',
    category: 'Crossover',
    generations: '2018–2024',
    primaryColors: ['אפור בטון', 'לבן', 'אדום', 'שחור'],
    status: 'pending',
  },
  {
    id: 'kia-stonic',
    makeEn: 'KIA',
    makeHe: 'קיה',
    modelEn: 'STONIC',
    modelHe: 'סטוניק',
    category: 'Crossover',
    generations: '2018–2024',
    primaryColors: ['לבן', 'אפור', 'צהוב', 'שחור', 'אדום'],
    status: 'pending',
  },
  {
    id: 'hyundai-kona',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'KONA',
    modelHe: 'קונה',
    category: 'Crossover',
    generations: '2018–2024',
    primaryColors: ['לבן', 'אפור כהה', 'שחור', 'אדום', 'כחול'],
    status: 'pending',
  },
  {
    id: 'toyota-chr',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'C-HR',
    modelHe: 'C-HR',
    category: 'Crossover',
    generations: '2017–2024',
    primaryColors: ['לבן פנינה דו-גווני', 'אפור טיטניום', 'שחור'],
    status: 'pending',
  },
  {
    id: 'peugeot-2008',
    makeEn: 'PEUGEOT',
    makeHe: 'פיג׳ו',
    modelEn: '2008',
    modelHe: '2008',
    category: 'Crossover',
    generations: '2016–2024',
    primaryColors: ['כתום פיוז׳ן', 'לבן פנינה', 'אפור', 'שחור'],
    status: 'pending',
  },
  {
    id: 'skoda-kamiq',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'KAMIQ',
    modelHe: 'קאמיק',
    category: 'Crossover',
    generations: '2020–2024',
    primaryColors: ['אפור בטון', 'לבן', 'כחול', 'שחור'],
    status: 'pending',
  },
  {
    id: 'suzuki-vitara',
    makeEn: 'SUZUKI',
    makeHe: 'סוזוקי',
    modelEn: 'VITARA',
    modelHe: 'ויטארה',
    category: 'Crossover',
    generations: '2015–2024',
    primaryColors: ['לבן', 'טורקיז', 'אפור מטאלי', 'שחור'],
    status: 'pending',
  },
  {
    id: 'nissan-juke',
    makeEn: 'NISSAN',
    makeHe: 'ניסאן',
    modelEn: 'JUKE',
    modelHe: 'ג׳וק',
    category: 'Crossover',
    generations: '2014–2024',
    primaryColors: ['אדום', 'לבן פנינה', 'שחור', 'אפור'],
    status: 'pending',
  },

  // ── 6. 7-Seaters & Large Family SUVs ──
  {
    id: 'mitsubishi-outlander',
    makeEn: 'MITSUBISHI',
    makeHe: 'מיצובישי',
    modelEn: 'OUTLANDER',
    modelHe: 'אאוטלנדר',
    category: '7-Seater',
    generations: '2014–2024',
    primaryColors: ['לבן פנינה', 'כסוף', 'שחור', 'אפור עכבר', 'חום'],
    status: 'pending',
  },
  {
    id: 'skoda-kodiaq',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'KODIAQ',
    modelHe: 'קודיאק',
    category: '7-Seater',
    generations: '2017–2024',
    primaryColors: ['לבן', 'אפור עכבר', 'שחור', 'כחול לבה'],
    status: 'pending',
  },
  {
    id: 'nissan-xtrail',
    makeEn: 'NISSAN',
    makeHe: 'ניסאן',
    modelEn: 'X-TRAIL',
    modelHe: 'אקס טרייל',
    category: '7-Seater',
    generations: '2015–2024',
    primaryColors: ['לבן פנינה', 'אפור מטאלי', 'שחור', 'ברונזה'],
    status: 'pending',
  },
  {
    id: 'kia-sorento',
    makeEn: 'KIA',
    makeHe: 'קיה',
    modelEn: 'SORENTO',
    modelHe: 'סורנטו',
    category: '7-Seater',
    generations: '2016–2024',
    primaryColors: ['לבן פנינה', 'שחור', 'אפור עופרת'],
    status: 'pending',
  },
  {
    id: 'hyundai-santafe',
    makeEn: 'HYUNDAI',
    makeHe: 'יונדאי',
    modelEn: 'SANTA FE',
    modelHe: 'סנטה פה',
    category: '7-Seater',
    generations: '2015–2024',
    primaryColors: ['לבן', 'שחור', 'אפור עכבר', 'חום'],
    status: 'pending',
  },

  // ── 7. Electric Vehicles (The New Market Leaders) ──
  {
    id: 'byd-atto3',
    makeEn: 'BYD',
    makeHe: 'בי-וואי-די',
    modelEn: 'ATTO 3',
    modelHe: 'אטו 3',
    category: 'EV',
    generations: '2022–2024',
    primaryColors: ['לבן גלישה', 'אפור טיפוס', 'כחול פארקור', 'אדום'],
    status: 'pending',
  },
  {
    id: 'geely-geometry-c',
    makeEn: 'GEELY',
    makeHe: 'ג׳ילי',
    modelEn: 'GEOMETRY C',
    modelHe: 'גאומטרי C',
    category: 'EV',
    generations: '2021–2024',
    primaryColors: ['לבן', 'כסוף', 'אפור כהה', 'תכלת'],
    status: 'pending',
  },
  {
    id: 'tesla-model-3',
    makeEn: 'TESLA',
    makeHe: 'טסלה',
    modelEn: 'MODEL 3',
    modelHe: 'מודל 3',
    category: 'EV',
    generations: '2021–2024',
    primaryColors: ['לבן פנינה', 'שחור', 'אפור כהה', 'כחול', 'אדום'],
    status: 'pending',
  },
  {
    id: 'tesla-model-y',
    makeEn: 'TESLA',
    makeHe: 'טסלה',
    modelEn: 'MODEL Y',
    modelHe: 'מודל Y',
    category: 'EV',
    generations: '2022–2024',
    primaryColors: ['לבן פנינה', 'שחור', 'אפור', 'כחול'],
    status: 'pending',
  },
  {
    id: 'mg-zs-ev',
    makeEn: 'MG',
    makeHe: 'אם-ג׳י',
    modelEn: 'ZS EV',
    modelHe: 'ZS חשמלי',
    category: 'EV',
    generations: '2020–2024',
    primaryColors: ['לבן', 'תכלת מטאלי', 'אדום', 'שחור'],
    status: 'pending',
  },

  // ── 8. Dedicated Off-Road & Enthusiast Icons ──
  {
    id: 'suzuki-jimny',
    makeEn: 'SUZUKI',
    makeHe: 'סוזוקי',
    modelEn: 'JIMNY',
    modelHe: 'ג׳ימני',
    category: 'SUV',
    generations: '2019–2024',
    primaryColors: ['ירוק קינטי', 'שנהב', 'אפור כהה', 'שחור', 'צהוב'],
    status: 'pending',
  },
  {
    id: 'toyota-landcruiser',
    makeEn: 'TOYOTA',
    makeHe: 'טויוטה',
    modelEn: 'LAND CRUISER',
    modelHe: 'לנד קרוזר',
    category: 'SUV',
    generations: '2010–2024',
    primaryColors: ['לבן פנינה', 'שחור מטאלי', 'כסוף', 'אפור'],
    status: 'pending',
  },
  {
    id: 'jeep-wrangler',
    makeEn: 'JEEP',
    makeHe: 'ג׳יפ',
    modelEn: 'WRANGLER',
    modelHe: 'רנגלר',
    category: 'SUV',
    generations: '2015–2024',
    primaryColors: ['שחור', 'לבן', 'אפור צבאי', 'אדום', 'ירוק זית'],
    status: 'pending',
  },
  {
    id: 'cupra-formentor',
    makeEn: 'CUPRA',
    makeHe: 'קופרה',
    modelEn: 'FORMENTOR',
    modelHe: 'פורמנטור',
    category: 'Crossover',
    generations: '2021–2024',
    primaryColors: ['אפור בטון מט', 'שחור מטאלי', 'כחול פטרול מט', 'לבן'],
    status: 'pending',
  },

  // ── 9. Executive & Premium Favorites ──
  {
    id: 'skoda-superb',
    makeEn: 'SKODA',
    makeHe: 'סקודה',
    modelEn: 'SUPERB',
    modelHe: 'סופרב',
    category: 'Family Sedan',
    generations: '2015–2024',
    primaryColors: ['שחור מנהלים', 'לבן', 'אפור כהה', 'כחול מגנטי'],
    status: 'pending',
  },
  {
    id: 'volkswagen-golf',
    makeEn: 'VOLKSWAGEN',
    makeHe: 'פולקסווגן',
    modelEn: 'GOLF',
    modelHe: 'גולף',
    category: 'Hatchback',
    generations: '2014–2024',
    primaryColors: ['לבן', 'אפור בטון', 'שחור', 'כחול'],
    status: 'pending',
  },
];
