/**
 * findingsRules.ts - Canonical findings definitions and explanations for Ototo
 */

import { Finding } from './types/index.js';

export const FINDINGS_CATALOG: Record<string, Omit<Finding, 'id'>> = {
  'F-STOLEN': {
    code: 'F-STOLEN',
    title: 'רכב רשום כגנוב במשטרה',
    severity: 'risk',
    category: 'blockers',
    detail: 'הרכב מסומן כגנוב פעיל. העסקה אינה בת-ביצוע ואין להמשיך ברכישה.',
    isBlocker: true,
  },
  'F-OFF-ROAD': {
    code: 'F-OFF-ROAD',
    title: 'רכב מבוטל / ירד מהכביש',
    severity: 'risk',
    category: 'blockers',
    detail: 'רישום הרכב בוטל לצמיתות במשרד התחבורה. הרכב אינו רשאי לנוע על הכביש.',
    isBlocker: true,
  },
  'F-DISABLED-TAG': {
    code: 'F-DISABLED-TAG',
    title: 'תו נכה פעיל על הרכב',
    severity: 'warn',
    category: 'blockers',
    detail: 'על הרכב רשום תו חניה לנכה. לא ניתן להעביר בעלות בדואר או באינטרנט עד שהמוכר ישחרר את התו במשרד הרישוי.',
    isBlocker: true,
    leverageText: 'המוכר נדרש לבטל את שיוך התו באתר משרד התחבורה לפני מועד העברת הבעלות.',
  },
  'F-RECALL-BLOCKING': {
    code: 'F-RECALL-BLOCKING',
    title: 'קריאת שירות בטיחותית (ריקול) שחוסמת העברת בעלות',
    severity: 'risk',
    category: 'blockers',
    detail: 'חלפו מעל 6 חודשים מפרסום הריקול הבטיחותי והוא טרם בוצע. על פי החוק משרד הרישוי חוסם העברת בעלות וטסט.',
    isBlocker: true,
    leverageText: 'המוכר מחויב לבצע את התיקון במוסך מורשה (התיקון מתבצע בחינם על חשבון היבואן).',
  },
  'F-RECALL-OPEN': {
    code: 'F-RECALL-OPEN',
    title: 'קריאת שירות בטיחותית (ריקול) פתוחה',
    severity: 'warn',
    category: 'history',
    detail: 'קיימת קריאת שירות פתוחה שטרם בוצעה. טרם חלפו 6 חודשים ממועד פרסומה ולכן אינה חוסמת עדיין, אך נדרשת לביצוע.',
    isBlocker: false,
    leverageText: 'לתיאום ביצוע ללא עלות במוסך מורשה יבואן.',
  },
  'F-KM-GAP': {
    code: 'F-KM-GAP',
    title: 'חשד לאי-התאמה או זיוף מד אוץ (ק״מ)',
    severity: 'risk',
    category: 'mechanical',
    detail: 'קריאת הק״מ בטסט הרישוי האחרון גבוהה מהק״מ המוצהר במודעה או בבדיקה.',
    leverageText: 'לדרוש היסטוריית טיפולים מלאה לבדיקת רצף הנסועה.',
  },
  'F-TOTAL-LOSS': {
    code: 'F-TOTAL-LOSS',
    title: 'אובדן להלכה / טוטאלוס משוקם',
    severity: 'risk',
    category: 'accidents',
    detail: 'הרכב הוגדר בעברו כנזק בטוטאלוס ושוקם לאחר מכן. ישנה השפעה מהותית על בטיחות וערך סחיר.',
    impactScore: -30,
    leverageText: 'ירידת ערך מהותית של כ-25% וסחירות מוגבלת בעתיד.',
  },
  'F-ACCIDENT-MAJOR': {
    code: 'F-ACCIDENT-MAJOR',
    title: 'תאונה עם ירידת ערך מהותית (מעל 15%)',
    severity: 'risk',
    category: 'accidents',
    detail: 'בדוח השמאי נקבעה ירידת ערך משמעותית המעידה על פגיעה במכלולים מרכזיים או שלדת הרכב.',
    leverageText: 'דרישה להפחתת מחיר מלאה לפי אחוז השמאי ולבדיקה קפדנית של איכות התיקון.',
  },
  'F-ACCIDENT-MODERATE': {
    code: 'F-ACCIDENT-MODERATE',
    title: 'תאונה עם ירידת ערך בינונית (5%-15%)',
    severity: 'warn',
    category: 'accidents',
    detail: 'קיימת תביעת ביטוח עם ירידת ערך מתונה בגין תיקוני מרכב ופחחות.',
    leverageText: 'הורדת מחיר במו״מ בהתאם לירידת הערך המתועדת.',
  },
  'F-ACCIDENT-MINOR': {
    code: 'F-ACCIDENT-MINOR',
    title: 'תביעת ביטוח קלה (עד 5% ירידת ערך)',
    severity: 'info',
    category: 'accidents',
    detail: 'תיקוני צבע, פגושים או שפשופים קלים שתוקנו במסגרת הביטוח.',
  },
  'F-ENGINE-SWAP': {
    code: 'F-ENGINE-SWAP',
    title: 'החלפת מנוע רשומה ברישיון הרכב',
    severity: 'warn',
    category: 'history',
    detail: 'מספר המנוע הנוכחי שונה מהמספר הרשום במקור בעת העלייה לכביש. המנוע הוחלף ואושר במשרד הרישוי.',
    impactScore: -25,
    leverageText: 'בירור סיבת ההחלפה, גיל המנוע המותקן ואחריות קיימת.',
  },
  'F-COLOR-CHANGE': {
    code: 'F-COLOR-CHANGE',
    title: 'שינוי צבע הרכב עודכן ברישיון',
    severity: 'warn',
    category: 'history',
    detail: 'הרכב נצבע מחדש בצבע שונה מצבע היצרן המקורי. צביעה כוללת מעוררת חשד לתיקון תאונה מקיף.',
    impactScore: -20,
    leverageText: 'שאלת המוכר לפשר הצביעה (שינוי אסתטי או תיקון פחחות כולל).',
  },
};
